trainer: ldm_trainer

autocast_bfloat16: true

max_iter: 300000
epoch_iter: 10000
eval_iter: 50000
save_iter: 50000
vis_iter: 50000

optimizers:
  encoder:
    name: adamw
    args: {lr: 1.e-4}
  renderer:
    name: adamw
    args: {lr: 1.e-4}

evaluate_ae: true